language: node_js
sudo: false
node_js:
- '9.0'
install:
- npm install
script:
- npm test
deploy:
  api_key:
		provider: heroku
    secure: qNIgamtCHbXGs+4M7hFQKCUoKgSOJ1vSgqbn44ef1t9GUWLIi1PLt/mMlJiA2nUqJneZg2P69Sb43p6PxXLN4v6sLE1cuDGqYLLKbmEwGCEykY0N+fKt4D9n2fryZPvAKiU6Msn5WgHjlHGQpypwBoWFzaXYri/1s5/M5I6BO4KDSyZDd+E7PtYFEl7c3Kzpj0I/UsYtAA5wBT2v4zjYlGkiSr8VBHLuUMWyiQw8zaS6G6lXOOSFmMora5kv4UXX6/bZ9c+jfmCsYiRJ+VEHvVRzf9Bdgk7T3ZKzXKIaeCf0sYtMV9hQWG7HMiTuQe3WPEmh/vuGlLlgvwmHZA0SlnuHTJlmFSMse5pSDtf/PurGIkW0jPgewpqNmndxO1ISaEvILMqz/7DWGUkey1Ei0yqFrneZAkWX4w5G40v9+RtTsaFvYeLW5+Fg4g132HYNFz2IRISUryZsZywyToFTVj6qWSw4KVKQ9kgMXYTCS1zyeA8C3xIc8ou4j+wpM3eSp49f+ccJMbJprsUKChGZt5OAbW3nsmuSDd0HVUh3t2QTdcdZozmblPIdOYrvbOHnHJmkh1okWfe8YkNO0qGHjVoldRpUf/9UKMakSLiHiPk9h7Q6mZsF82LEwMusPv+EMEODCEfTP1PIpKPqRWLqxWgC2Xa3KsOI0v/kipVPMGE=
		app: almost-thea-api
